receivers:
  loadgen:

exporters:
  otlp:
    endpoint: "${env:ELASTIC_APM_SERVER_URL}"
    headers:
      Authorization: "Bearer ${env:ELASTIC_APM_SECRET_TOKEN}"
    sending_queue:
      enabled: false
    timeout: 60s
  debug:


processors:
  transform:
    log_statements:
      - context: log
        statements:
          - set(time, Now())
    metric_statements:
      - context: datapoint
        statements:
          - set(time, Now())
    trace_statements:
      - context: span
        statements:
          - set(start_time, Now())
          - set(end_time, Now())
          # The worst way to generate a random trace / span ID, but is the simplest in OTTL
          - set(trace_id.string, Substring(MD5(UUID()), 0, 32))
          - set(span_id.string, Substring(MD5(UUID()), 0, 16))
          - set(parent_span_id.string, Substring(MD5(UUID()), 0, 16))
      - context: spanevent
        statements:
          - set(time, Now())

  ratelimit:
    strategy: records
    rate: 1000
    burst: 1000


service:
  pipelines:
    logs:
      receivers: [loadgen]
      processors: [transform]
      exporters: [otlp, debug]
    metrics:
      receivers: [loadgen]
      processors: [transform]
      exporters: [otlp, debug]
    traces:
      receivers: [loadgen]
      processors: [transform]
      exporters: [otlp, debug]
#  telemetry:
#    logs:
#      level: debug
