receivers:
  loadgen:
  nop:

exporters:
  otlp:
    endpoint: "http://localhost:8200"
    sending_queue:
      enabled: false
    timeout: 60s
  otlphttp:
    endpoint: "http://localhost:8200"
    sending_queue:
      enabled: false
    timeout: 60s
  nop:

processors:
  transform/rewrite:  # Rewrite telemetry to increase cardinality
    trace_statements:
      - context: span
        statements:
          # The worst way to generate a random ID, but is the simplest in OTTL
          # Only randomize trace ID such that span relationships are still maintained
          - set(trace_id.string, Substring(MD5(UUID()), 0, 32))

service:
  pipelines:
    logs:
      receivers: [loadgen]
      processors: [transform/rewrite]
      exporters: [otlp] # this will be set dynamically to otlp or otlphttp depending on config
    metrics:
      receivers: [loadgen]
      processors: [transform/rewrite]
      exporters: [otlp] # this will be set dynamically to otlp or otlphttp depending on config
    traces:
      receivers: [loadgen]
      processors: [transform/rewrite]
      exporters: [otlp] # this will be set dynamically to otlp or otlphttp depending on config
