receivers:
  loadgen:

exporters:
  otlp:
    endpoint: "localhost:0"
    sending_queue:
      enabled: false
    timeout: 60s
  otlphttp:
    endpoint: "localhost:0"
    sending_queue:
      enabled: false
    timeout: 60s

processors:
  transform/rewrite:  # Rewrite telemetry to increase cardinality
    trace_statements:
      - context: span
        statements:
          # The worst way to generate a random ID, but is the simplest in OTTL
          # Only randomize trace ID such that span relationships are still maintained
          - set(trace_id.string, Substring(MD5(UUID()), 0, 32))
